index:
  name: products
  prefix: product:

fields:
    # define tag fields
    tag:
        - name: gender
        - name: category
    # define vector fields
    vector:
        - name: img_vector
          dims: 512
          type: float32
          algorithm: hnsw
          distance_metric: cosine
        - name: text_vector
          dims: 768
          type: float32
          algorithm: hnsw
          distance_metric: cosine